package su.nepom.budget.desktop

import java.util.Properties

/** Build metadata generated by the `generateBuildInfo` Gradle task. */
object BuildInfo {
    private val props = Properties().apply {
        BuildInfo::class.java.getResourceAsStream("/build-info.properties")?.use { load(it) }
    }

    val version: String = props.getProperty("version", "unknown")
    val revision: String = props.getProperty("revision", "unknown")
    val dirty: Boolean = props.getProperty("dirty", "false").toBoolean()
    val buildTime: String = props.getProperty("buildTime", "unknown")

    fun summary(): String = buildString {
        appendLine("Версия: $version")
        append("Ревизия: $revision")
        if (dirty) append(" (рабочая копия была не чистая)")
        appendLine()
        append("Дата сборки: $buildTime")
    }
}
